# -*- coding: utf-8 -*-
"""eligible for vote.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jum4hFwvUCcHhmUxbzAAQ8fObHhVz_Rg
"""

def is_valid_age(age_input):
    try:
        age = int(age_input)
        if age < 0 or age > 120:
            print("🤔 That doesn't seem like a valid human age.")
            return None
        return age
    except ValueError:
        print("❌ Please enter a valid number for age.")
        return None

def check_eligibility(age, is_citizen):
    if age >= 18 and is_citizen:
        print("✅ Congratulations! You're eligible to vote. Make your voice count! 🗳️")
    elif age >= 18 and not is_citizen:
        print("⚠️ You're old enough, but only citizens are allowed to vote.")
    elif age < 18:
        print(f"⏳ You're just {age} years old. Wait a few more years to vote!")
    else:
        print("⚠️ Unable to determine eligibility.")

def main():
    print("\n🗳️ Welcome to the SmartVote Eligibility Checker 🗳️\n")

    age_input = input("Enter your age: ")
    age = is_valid_age(age_input)

    if age is None:
        return  # Exit if invalid age

    citizen_input = input("Are you a citizen of this country? (yes/no): ").strip().lower()
    is_citizen = citizen_input in ['yes', 'y']

    print("\n" + "-" * 50)
    check_eligibility(age, is_citizen)
    print("-" * 50 + "\n")

if __name__ == "__main__":
    main()

